# Generated by Django 5.1.3 on 2024-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product_active_product_metadata_paymentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
